variables:
  # Keep in sync with include/ref.
  TESTS_SHA: 85b4722

include:
  - project: info-process-tests
    file: test.yml
    # Keep in sync with TESTS_SHA.
    ref: 85b4722

.only_master_and_all_mrs: &only_master_and_all_mrs
  only:
    variables:
    - $CI_COMMIT_REF_NAME == "master"
    - $CI_PIPELINE_SOURCE == "merge_request"

pytest:
  image: debian:trixie
  <<: *only_master_and_all_mrs
  before_get_sources:
    - apt -y update &>/dev/null
    - apt -y install --no-install-recommends python3 python3-pip python3-venv git &>/dev/null
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install ".[test]"
    - pytest
